### ISSUE TITLE
Building on Windows corrupts shell script end of line markers

### ISSUE THREAD

**Issue by bnevis-i** [edgexfoundry/developer-scripts#156]
# 🐞 Bug Report

### Description
In PR https://github.com/edgexfoundry/developer-scripts/pull/147 it was determined that the Consul health checking shell scripts can be corrupted if the container is being built on a Windows machine.  This is because when the code is checked out on Windows, many people have automatic EOL conversions turned on, which ends up changing newlines from LF to CRLF.  The corrupted shell scripts are then incorporated into the container image during a docker build.

### Proposed fix
Introduce a .gitattributes to prevent the automatic conversion from occurring.

For example:
`.gitattributes`
```
scripts/*.sh -text
```

See also https://www.edwardthomson.com/blog/git_for_windows_line_endings.html

**Comment by rsdmike** [comment]
We could also improve the robustness of the docker images by ensuring linux line endings when its built which could easily be done with something like `dos2unix`. Example:
```
RUN apt-get update && apt-get install -y dos2unix

COPY docker-entrypoint.sh /entrypoint.sh

RUN dos2unix /entrypoint.sh && apt-get --purge remove -y dos2unix && rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["/entrypoint.sh"]
```

^^^ very rudimentary example, but hopefully get the idea. Would just eliminate the issue entirely, should be simple enough as well since we use multi-stage builds we don't have to the include the remove part.  I develop pretty much exclusively on windows, so not having to worry about line endings would be great :) +1 for DX.

**Comment by bnevis-i** [comment]
For the above to work for target containers built from `scratch`, the build container would have to run this code to sanitize the script, and then the sanitized script would then have to be copied from the build container into the deployment container.  Doing as suggested above in the deployment container would introduce additional attack surface and size to several of the existing containers.

**Comment by rsdmike** [comment]
Yup, that's correct. Wouldn't suggest doing that at all, copying your build operations and dependencies in to your deployment would defeat the purpose indeed!
