### ISSUE TITLE
Issue with nightly compose file (no-secty)

### ISSUE THREAD

**Issue by rsdmike** [edgexfoundry/developer-scripts#157]
When bringing up `docker-compose-nexus-no-secty` in the nightly folder most services fail to initialize with the error below.  I had @lenny-intel reproduce as well, must clear all volumes and images to recreate. It's a bit misleading since security should be disabled entirely and shouldn't try to look for a secret store since `EDGEX_SECURITY_SECRET_STORE: "false"`. 

```
level=ERROR ts=2019-10-23T22:22:22.4998716Z app=edgex-core-command source=logger.go:105 msg="logTarget cannot be blank, using stdout only"
level=ERROR ts=2019-10-23T22:22:22.5696239Z app=edgex-core-command source=secret.go:58 msg="unable to parse secret store configuration: open /vault/config/assets/resp-init.json: no such file or directory"
```

@jim-wang-intel Can you take a look?

**Comment by jim-wang-intel** [comment]
It looks like the latest change on the Common Bootstrapper breaks the behavior of the original environment variable `EDGEX_SECURITY_SECRET_STORE`.   In this particular error given above from @rsdmike, the Bootstraper from core-command always uses the secrets provider even when the env is off.  See this: https://github.com/edgexfoundry/edgex-go/blob/master/cmd/core-command/main.go#L62   

@tingyuz, @michaelestrin @AnthonyMBonafide I think we should fix the behavior of how bootstrap utilizes that env so that in no-security mode, we should not instantiate the secret provider at all.

**Comment by michaelestrin** [comment]
Nightly builds triggered manually after https://github.com/edgexfoundry/edgex-go/pull/1987 was merged.  After several failed builds because https://nexus3.edgexfoundry.org/ went down, those have just completed and updated nexus images are available.  Please retest and advise if you're still experiencing the originally reported issue.  @rsdmike @jim-wang-intel

**Comment by lenny-intel** [comment]
@michaelestrin , I just verified that fixed it!! One issue with testing these is docker doesn't pull the latest images tagged with `1.1.0` if an older image with that tag already exist on your system. :-( 
@lranjbar , would it be better to tag the images with `latest` tag to avoid this issue?

**Comment by jim-wang-intel** [comment]
@michaelestrin that edgexfoundry/edgex-go#1987 does solve the issue. Thanks for fixing that. 

IMHO, one note for future is that we could instantiate different BootStrapperHandler right on the `main.go` or another wrapper around that first argument of handler when the environment variable is `false` instead of `secretProvider` handler.  

@lenny-intel  maybe in the command line we always pull first before up no matter what?  
```sh
docker-compose -f docker-compose-nexus-no-secty.yml pull && docker-compose -f docker-compose-nexus-no-secty.yml up
```

**Comment by michaelestrin** [comment]
> Thanks for fixing that.

Thank you for validating the fix.  I'm sorry I missed that in my PR review yesterday.

> IMHO, one note for future is that we could instantiate different BootStrapperHandler right on the `main.go` or another wrapper around that first argument of handler when the environment variable is `false` instead of `secretProvider` handler.

The existing secret bootstrap handler implementation encapsulates the implementation details around whether security is enabled or disabled.  It provides a simple contract for getting Mongo credentials.  Not sure why we'd want to have any other part of the service be aware of whether security is enabled or disabled.

**Comment by lranjbar** [comment]
> @michaelestrin , I just verified that fixed it!! One issue with testing these is docker doesn't pull the latest images tagged with `1.1.0` if an older image with that tag already exist on your system. :-(
> @lranjbar , would it be better to tag the images with `latest` tag to avoid this issue?

No, latest is ambiguous when you have multiple branches being built. For those with pipeline jobs you should use the tag that matches the branch name.
