### ISSUE TITLE
docker-edgex-mongo fails to read secret stores in nightly-nexus docker-compose

### ISSUE THREAD

**Issue by jim-wang-intel** [edgexfoundry/developer-scripts#167]
During the initialization of docker-compose, the `docker-edgex-mongo` fails to read secret stores data from the secret store vault.   It results in an exited status code `1` for mongo.

Error message: 
```failed to read secret stores data for '/v1/secret/edgex/mongo/logging' path: Unable to obtain secrets from underlying data-store: Received a '404' response from the secret store```

Note that, the path can be different from run to run, kind of random.  In this example, it is `/v1/secret/edgex/mongo/logging` but last time I saw it is from `application-service`. 

## Steps to reproduce:
 1. run docker-compose:
```sh
$ docker-compose -f docker-compose-nexus.yml pull && docker-compose -f docker-compose-nexus up -d
```

 2. Wait until the docker-compose up finished

 3.  $ docker ps -a | grep edgex-mongo
one should see something like the following and note that the `docker-edgex-mongo` exits with status code 1
```
2e5768be52df        nexus3.edgexfoundry.org:10004/docker-edgex-mongo:1.1.0                           "/edgex-mongo/bin/ed…"   50 seconds ago       **Exited (1)** 48 seconds ago                  
```

4. `docker logs 2e57` shows the error message logs from `edgex-mongo` service:
```
level=ERROR ts=2019-10-25T16:11:47.970246932Z app=edgex-mongo source=logger.go:105 msg="logTarget cannot be blank, using stdout only"
level=INFO ts=2019-10-25T16:11:47.971982382Z app=edgex-mongo source=main.go:32 msg="starting edgex-mongo process ..."
level=INFO ts=2019-10-25T16:11:47.972063005Z app=edgex-mongo source=config.go:38 msg="loading configuration considering the secret store"
level=INFO ts=2019-10-25T16:11:47.972122705Z app=edgex-mongo source=init.go:47 msg="config file location: res/docker/configuration.toml"
level=ERROR ts=2019-10-25T16:11:48.027377896Z app=edgex-mongo source=config.go:71 msg="failed to read secret stores data for '/v1/secret/edgex/mongo/logging' path: Unable to obtain secrets from underlying data-store: Received a '404' response from the secret store"
level=ERROR ts=2019-10-25T16:11:48.027432695Z app=edgex-mongo source=main.go:57 msg="edgex-mongo failed because of: Unable to obtain secrets from underlying data-store: Received a '404' response from the secret store"
```

**Comment by jim-wang-intel** [comment]
One can put the restart policy on docker-compose file to relief and heal the situation: 
```yaml
restart: "on-failure: 5"
```
However, this just cure the problem from the surface; not the root-cause.
@difince  @tingyuz

**Comment by difince** [comment]
@jim-wang-intel 
It looks that at the time edgex-mongo tries to read the secrets, the secrets are still not present because vault-worker haven't yet done its work.
I could add what you suggest:

> restart: "on-failure: 5"

or What I was thinking - to add a retry mechanism inside the edgex-mongo  for 30 seconds ... 
Do you have preferences ?

**Comment by difince** [comment]
I used your approach as less error prone, taking in consideration that this is a fix in the last moment

**Comment by difince** [comment]
The issue will be handled by @anonymouse64

**Comment by anonymouse64** [comment]
This will need a small PR to docker-edgex-mongo to add curl to the docker image.

**Comment by anonymouse64** [comment]
Hmm actually this is a bit more complicated, let's discuss this afternoon when we discuss what to do about go-mod-secrets, it's actually the same problem, mongo is essentially the same as the core services in racing to access secrets after vault is unsealed while security-secretstore-setup is racing to write those tokens.

What's complicated about this is that we don't currently have a clear way to designate that security-secretstore-setup has uploaded all the certs, we can tell when it's initialized and unsealed Vault by just asking Vault directly, but for us to check with vault whether the keys are there requires authorization to access those keypaths or some modification to security-secretstore-setup itself. 

My basic suggestion is to just have go-mod-secrets loop trying to access the key rather than have other services loop waiting for the keys to exist because they don't necessarily need access to the keys itself, they just need to know whether the keys have been uploaded. An alternative to this is to have security-secretstore-setup drop a .complete file somewhere like what security-secrets-setup does.

**Comment by bnevis-i** [comment]
Discussed in F2F.  Agree that having secret clients block on secret availability is more scaleable and less risky than having a health monitoring script that has the ability to read almost every secret out of the secret store.  The health monitoring alternative are incompatible with secrets hardening planned for Geneva and the implementation would have to be ripped out of and replaced , whereas the blocking code would be a permanent fix.
