### ISSUE TITLE
Core services fails to start as they try to read their secrets-token.json before it is created

### ISSUE THREAD

**Issue by difince** [edgexfoundry/developer-scripts#230]
Core services fails to start because they are faster and try to read  **/tmp/edgex/secrets/edgex-*/secrets-token.json** before it is created by **security-secretstore-setup** (vault-worker)
- core-command, 
- core-data, 
- core-metadata, 
- edgex-support-scheduler, 
- edgex-support-notifications, 
- edgex-support-logging

Possible exceptions: 

- `level=ERROR ts=2020-02-27T14:55:53.486218133Z app=edgex-core-command source=secret.go:58 msg="unable to parse secret store configuration: open /tmp/edgex/secrets/edgex-core-command/secrets-token.json: no such file or directory"` -if the file does not exists at all (still not created by vault-worker)

- ` level=ERROR ts=2020-02-28T13:42:30.836198661Z app=edgex-core-command source=secret.go:67 msg="unable to create SecretClient: HTTP response with status code 503, message: failed to lookup token"` - if the file exists, but it is still not updated by vault-worker with the new **client_token**

So, all containers that mount **/tmp/edgex/secrets/service-name** needs to wait on vault-worker to finish its work.

**Comment by bnevis-i** [comment]
Copied from issue 229:

Currently mongo as well as several other containers that use Vault tokens have special init-blocking code defined in the docker-compose to avoid this issue.

```
    entrypoint: >
      /bin/sh -c
      "until /consul/scripts/consul-svc-healthy.sh security-secretstore-setup; do sleep 1; done;
      /edgex-mongo/bin/edgex-mongo-launch.sh"
```

**Comment by bnevis-i** [comment]
@michaelestrin, I would like to get your input on this issue.

I have spent some time looking at this and have come up with several possible ways to fix this issue.  Which of these do you think is best?

1. Add retry loops for files existing, secrets not being in the secret store, etc.  I think this is awkward because in the cloud one normally has databases and secrets provisioned ahead of time, but on the edge we are doing such provisioning in the nick of time.  I also think it would make the code pretty messy and it wouldn't be obvious to people why were are retrying file I/O, etc.

2. Add the mentioned entrypoint hooks into the affected containers, and change the corresponding Dockerfile's to inherit from an Alpine image.  (Many of these core and support services currently inherit from scratch.)  Theoretically, with docker layers, this won't really cost much extra space as long as everyone is using the same base layer.  Downside is that this introduces attack surface into the containers and also means we'll start seeing snyk reports when these containers get old.

3. Modify `consul-svc-healthy` which Anthony already made into a binary to be able to sleep on its own, wait for multiple services, and then when dependencies are satisfied, exec() another command passed to it like `sh -c` does.

4. Modify the bootstrap such that we can configure components to wait for certain services to be healthy before they start their main execution, borrowing code from consul-svc-healthy.  For example, any component that uses secrets would automatically wait on security-secretstore-setup.

I lean towards #4, but #2 could be done if a quick fix is needed.

cc: @tingyuz

**Comment by michaelestrin** [comment]
`consul-svc-healthy` -> https://github.com/edgexfoundry/docker-edgex-consul/pull/16

**Comment by michaelestrin** [comment]
> Which of these do you think is best?

Security initialization and set up is contrived.

Given that, of all the options number four seems most correct.  It does require go-mod-registry.  Does security currently take a dependency on the registry?  If not, I'm not sure whether or not we would want to add one.

If you go this route, I'd suggest a new bootstrap handler in go-mod-bootstrap/bootstrap/handlers that takes a list of service dependencies and waits on each to initialize before returning.  This handler could then be reused across services in the call to Run() -- perhaps passed as the first bootstrap handler in the `handlers []interfaces.BootstrapHandler` parameter to ensure dependent services are ready.

**Comment by bnevis-i** [comment]
> Does security currently take a dependency on the registry? If not, I'm not sure whether or not we would want to add one.

Security services themselves: There is not a dependency on the registry per-se, but Consul health checks are required to ensure that service services are brought up in the correct order.  Also, Vault uses Consul as a backend storage engine.

Non-security services: Do not directly depend on the registry today as they can get the configuration from TOML.  Services that consume secrets from the secret store have this dependency indirectly (see above).

I am hesitant to introduce this direct dependency even though it exists indirectly.

Perhaps option 5:

5. Modify the secrets bootstrapper to wait some amount of time, when the secrets engine is enabled, for a VALID secrets token (exists on disk, is not expired, revoked, etc.)

**Comment by jinlinGuan** [comment]
Once [developer-scripts#232](https://github.com/edgexfoundry/developer-scripts/pull/232) is merged, [blackbox-testing#401](https://github.com/edgexfoundry/blackbox-testing/issues/401) and [developer-scripts/#228](https://github.com/edgexfoundry/developer-scripts/issues/228) will be fixed. 
This issue is going to block blackbox-testing Jenkins jobs.

**Comment by bnevis-i** [comment]
> This issue is going to block blackbox-testing Jenkins jobs.

It shouldn't because the blackbox testing scripts have a hard-coded sleep delay.  However, `docker-compose up -d` is in a race.

**Comment by cloudxxx8** [comment]
right, I saw the sleep delay.
thanks, @bnevis-i 
https://github.com/edgexfoundry/blackbox-testing/blob/master/deploy-edgeX.sh#L52-L75
