### ISSUE TITLE
EdgeX Foundry UI doesn't work 

### ISSUE THREAD

**Issue by cowboylux** [edgexfoundry/developer-scripts#319]
Step to reproduce:
Run EdgeX via docker-compose:
_sudo docker-compose -f docker-compose-nexus-arm64.yml up -d_
Run ExdeX Console via docker-compose:
_sudo docker-compose -f docker-compose-nexus-ui.yml up -d_
Open EdgeX console via browser:
<img width="1386" alt="Screen Shot 2020-09-25 at 12 40 02" src="https://user-images.githubusercontent.com/25590798/94252571-c8c1a800-ff2c-11ea-8023-29db895dfebf.png">

ExdeX Console container logs:
<img width="1001" alt="Screen Shot 2020-09-25 at 12 40 36" src="https://user-images.githubusercontent.com/25590798/94252629-dbd47800-ff2c-11ea-86db-d6ce36162954.png">

Release: Nightly Build

**Comment by lenny-intel** [comment]
@cowboylux , this is because they way you are starting is creating the docker network different than what the US compose file is expecting. 

We have help commands in the `Makefile` that make this easier or you can add the `-p=edgex`  option to each of your docker-compose commands.

Also I notice you are using the ARM64 version of the main compose file, but not for the UI. These should both be ARM64 or both not ARM64.

The make commands are:

- `make run` or `make run arm64` 
- `make run-ui` or `make run-ui arm64` 

These commands make sure both the main compose and the UI compose are started using the network expected in both compose files.

**Comment by lenny-intel** [comment]
@cowboylux , please confirm my instructions above resolve your issue.

**Comment by jpwhitemn** [comment]
@cowboylux - I am closing this issue, but if you find @lenny-intel comments do not address your issue, please reopen it and provide more details.
