### ISSUE TITLE
Upgrade Docker Compose to version 3

### ISSUE THREAD

**Issue by rtmaster** [edgexfoundry/developer-scripts#39]
I see that the Docker Compose file is version 2 (supporting Docker Engines 1.10.0+). See https://docs.docker.com/compose/compose-file/compose-versioning/#compatibility-matrix

The recommended Docker Compose file from Docker is version 3 (supporting Docker Engines 1.13.0+) which would allow also EdgeX to be deployed via Swarm.
I did a comparison between the changes in the syntax upgrading from 2 to 3 and it seems as the only deprecated command that was used in the EdgeX file is "volumes_from" (see https://docs.docker.com/compose/compose-file/compose-versioning/#upgrading)

Can we generate a Docker Compose version 3 file?

**Comment by jpwhitemn** [comment]
Thanks for seeing this and bringing it to the attention of the EdgeX community rtmaster!
If you would like to test it out and can contribute those changes, the community would be extremely grateful.  Otherwise,so that you get credit, would you mind filing an issue against the developer-scripts repo of EdgeX ( https://github.com/edgexfoundry/developer-scripts/issues )?  I will submit the request if you would prefer not to submit the issue. 
We are currently getting some of our first Go services ready for our California Preview release.  After that, I believe the community can address/fix this issue relatively quickly after the release is out.
Jim White


 

    On Wednesday, January 10, 2018, 2:16:10 PM CST, rtmaster <notifications@github.com> wrote:  
 
 
I see that the Docker Compose file is version 2 (supporting Docker Engines 1.10.0+). See https://docs.docker.com/compose/compose-file/compose-versioning/#compatibility-matrix

The recommended Docker Compose file from Docker is version 3 (supporting Docker Engines 1.13.0+) which would allow also EdgeX to be deployed via Swarm.
I did a comparison between the changes in the syntax upgrading from 2 to 3 and it seems as the only deprecated command that was used in the EdgeX file is "volumes_from" (see https://docs.docker.com/compose/compose-file/compose-versioning/#upgrading)

Can we generate a Docker Compose version 3 file?

**Comment by jpwhitemn** [comment]
Just saw the issue already posted.  Thanks rtmaster!!
 

    On Wednesday, January 10, 2018, 2:16:10 PM CST, rtmaster <notifications@github.com> wrote:  
 
 
I see that the Docker Compose file is version 2 (supporting Docker Engines 1.10.0+). See https://docs.docker.com/compose/compose-file/compose-versioning/#compatibility-matrix

The recommended Docker Compose file from Docker is version 3 (supporting Docker Engines 1.13.0+) which would allow also EdgeX to be deployed via Swarm.
I did a comparison between the changes in the syntax upgrading from 2 to 3 and it seems as the only deprecated command that was used in the EdgeX file is "volumes_from" (see https://docs.docker.com/compose/compose-file/compose-versioning/#upgrading)

Can we generate a Docker Compose version 3 file?

**Comment by jpwhitemn** [comment]
The California preview release, nexus and latest docker compose files have all been moved to 3.  Left the compose files for Barcelona 2.0 and 2.1 at compose 2
