### ISSUE TITLE
docker-compose.yml does not work

### ISSUE THREAD

**Issue by jeremylin06** [edgexfoundry/developer-scripts#61]
docker-compose.yml does not work, because of no "edgexfoundry/docker-core-config-seed-go:latest" image. hub.docker.com has only "edgexfoundry/docker-core-config-seed-go:test" and "edgexfoundry/docker-core-config-seed-go:0.6.0". The same problem to other "-go" images.

**Comment by jpwhitemn** [comment]
With PR coming, I am making changes to the docker-compose.yml so that it is essentially the same as the docker-compose-california-0.6.0 so that it works, but this is problematic.  We need the "latest" tag applied to the latest docker image we create.  @JPWKU - can we have the CI process add the latest tag to the latest images when dumped into Docker Hub?
